- overview.rst
> Adjusted trial length to match reality

- gdpr-platform-developer-docs.rst
> Spelling error in GDPR platform / Developer documentation / GDPR consent

- changelog.rst
- configuration.rst
Also fixed incorrect composite entity id.
> IS-7856: Added changelog for index version 2

- DTLReferenceGuide.rst
- changelog.rst
- configuration.rst
- deprecations.rst
- swagger_public.yaml
And the "reference" DTL function has been deprecated.
> IS-7701: Sink compaction, merge source, rest system and sink no longer experimental

- concepts.rst
improve description of installation and configuration of sesam client
> improve description of installation and configuration of sesam client

- changelog.rst
- configuration.rst
Adding docs for using the REST system in a transform
> Improve docs rest transform

- best-practice.rst
formatting-fixes: cleanup of some formatting issues
> formatting-fixes: Merge formatting-fixes to master

- changelog.rst
- configuration.rst
…rom_table SQL sink properties
> IS-10295: documented the new skip_identity_columns property

- self-hosted.rst
And: IS-10567: document how to migrate from topology to agent in docs.sesam.io
> IS-10568: Added warnings about not opening outbound firewall

- configuration.rst
> Fix typos in REST source

- requirements.txt
- training/030_dtl/020_Beginner.rst
Fleshed out section "DTL in practice".
> #207: Merge 207 to training

- .github/ISSUE_TEMPLATE/training.md
- DTLReferenceGuide.rst
- changelog.rst
- configuration.rst
- requirements.txt
- roadmap.rst
- self-hosted.rst
- training/010_architecture_and_concepts/020_Beginner.rst
Formatted figure, adde figure text and corrected format of _id
> #198: Formatting section 1.1.5

- training/010_architecture_and_concepts/020_Beginner.rst
- training/030_dtl/020_Beginner.rst
Architecture & Concepts: Beginner - Datasets
> #234: Merge 234 to training

- _templates/css/sesam.css
- _templates/layout.html
- training/README.md
- Add _templates/css/sesam.css to contain custom CSS
- Update _templates/layout.html to use custom CSS
- Update README.md with custom CSS setup and usage instructions
> Add custom CSS support

- features.rst
- index.rst
Please read in sales mode :)
And if you can: Add it to the main many under "Core concepts" as a separate topic
> Added page to connect sales to features

- _templates/css/sesam.css
- management-studio.rst
- training/010_architecture_and_concepts/020_Beginner.rst
- Added some summaries
- Tweaked x-refs, tried to make them more consistent and easier to understand
- Cleaned up figures and added a bit of custom CSS
- Added a few new ref anchors to improve x-refs
This is not complete, but would like your input. Are these tweaks something we should move forward with?
> #310: Architecture: Beginner: Section summaries and ref cleanup

- training/050_microservices/020_Beginner.rst
Previous version of this branch was based off of branch 312.
This one is branched of off training to make it more independent.
> #313: Merge Why use Microservices in Sesam? into training

- training/010_architecture_and_concepts/020_Beginner.rst
#308: Tidy up Architecture & Concepts: Beginner: Systems
> #308: Merge Architecture: Beginner: Systems into training

- training/050_microservices/020_Beginner.rst
Consistent refs to Sesam's community at GitHub & DockerHub
> Merge microservices-consistent-refs into training

- training/050_microservices/020_Beginner.rst
https://github.com/datanav/docs/blob/training/training/010_architecture_and_concepts/020_Beginner.rst#naming-conventions
> #318 : Deleting this section as it is obsolete

- training/020_systems/020_Beginner.rst
- training/050_microservices/020_Beginner.rst
Correcting error on ref line inn Systems -> Beginner.rst file when making seealso section on this PR.
> #317 : Adding Categories of Microservices for Beginners

- training/README.md
> #302: Update training/README.md to include a styleguide

- DTLReferenceGuide.rst
- changelog.rst
- collecting_data.rst
- concepts.rst
- configuration.rst
- data-enrichment.rst
- deprecations.rst
- entitymodel.rst
- extension-points.rst
- getting-started.rst
- index.rst
- json-push.rst
- quick-reference.rst
- rdf-support.rst
People have been asking for better navigation, so I’ve created this quick reference document that should make it easier to find and navigate between functions and config types. It’s an experiment for now and probably needs a bit more tuning, but it’s a start.
> Added configuration and DTL quick reference

- DTLReferenceGuide.rst
Example with only string values and link added
> Adding ASCII dimension to using ["min" .. ]

- training/020_systems/020_Beginner.rst
- training/020_systems/030_Novice.rst
Changed syntax on tasks for Systems : Beginner as well, as these were not correct
> #428 : Adding tasks

- training/020_systems/030_Novice.rst
- training/050_microservices/030_Novice.rst
Found a missing "Summary" section in Novice -> Microservice which I also fixed.
> 426 : Adding section

- DTLReferenceGuide.rst
- changelog.rst
The subsets bugfix should be in weekly now. Restore the docs for it.
> Revert "IS-11760: temporarily revert changes related to subsets->prefilters r…"

- changelog.rst
See https://github.com/datanav/lake/pull/4089.
> Document addition of domain name validation

- changelog.rst
- configuration.rst
Document addition of header functionality in HTTP transform (https://github.com/datanav/lake/pull/4093)
> IS-11786: Update documentation related to issue

- core-principles.rst
- index-datamodelling.rst
- index-dataplatforms.rst
- index-operations.rst
- index-synchronization.rst
- tools.rst
> Added introductions to topics in user guide

- index-datamodelling.rst
- index-dataplatforms.rst
- index-operations.rst
- index-synchronization.rst
- tools.rst
> Add toc titles

- DTLReferenceGuide.rst
- Prefixed title with 'Built-in' to clarify what these variables are.
- Cleaned up intro summary.
- Added entry for _B.
> Update DTL variables section

- _static/css/custom.css
Minor CSS improvements for smaller screens.
> Minor CSS improvements

- changelog.rst
Added user reported experience changes to clustered architecture changes
> Added behavior changes to clustered architecture

- data-architecture.rst
- index-whatis.rst
> Rename Data Product

- index-developer.rst
> Renamed to Documentation

- _static/css/custom.css
- guide-getting-started.rst
> Updated layout for Getting started

- _static/css/custom.css
Changes visited link color for Start tutorial button.
> Changed :visited color

- _static/css/custom.css
- guide-getting-started.rst
- tutorial-signup.rst
- tutorial-upload-baseline-config.rst
> Enhance tutorials: Getting started

- _static/css/custom.css
> Dark top menu

- DTLReferenceGuide.rst
Renaming to better reflect the contents of the section.
> Rename section 'Namespace' to 'Namespace aware function'

- conf.py
- docker/default.conf
- requirements.txt
Graphics will be shown once docs are deployed.
> Add 404 page

- _static/css/custom.css
- custom-data-source.rst
> Added new tutorials to custom data sources

- custom-data-source.rst
Deleted change tracking (repetitive) and fixed the text.
> Deleted "change tracking"

- tutorial-getting-started-collect.rst
> added some text improvments from feedbackD

- guide-create-first-synchronization.rst
- tutorial-getting-started-collect.rst
> minor changes

- _static/css/custom.css
- conf.py
- requirements.txt
> Add copy button to code blocks

- tutorial-getting-started-enrich.rst
> added namespaced to objectives

- conf.py
- requirements.txt
> Add redirect extension

- concepts.rst
> Concepts improvement

- index-developer.rst
- index.rst
Move features out of documentation and add the link on top menu
> Move features out of documentation

- changelog.rst
- concepts.rst
- configuration-pipes.rst
- configuration-sinks-dataset.rst
- configuration-sources-http.rst
- dtl/dtl-functions-namespaced-identifiers.rst
- dtl/dtl-functions-paths.rst
- dtl/dtl-functions-transforms.rst
- dtl/namespaces.rst
- features/circuit-breakers.rst
- features/compaction-feature.rst
- features/completeness-feature.rst
- features/durable-data.rst
- features/namespaces.rst
- json-pull.rst
- management-studio.rst
> moved pipe features to features and created a list of features there instead

- _static/css/custom.css
> CSS: added background color menu button

- _static/css/custom.css
- features/durable-data.rst
> Improved documentation about Durable data

- configuration-pump.rst
- features/change-tracking.rst
> changed name tracking feature text

- index-developer.rst
- index-whatis.rst
> Moved roadmap to what is sesam

- features/data-management-features.rst
- features/data-synchronization-features.rst
- product-features.rst
Move change tracking from data management to data synchronization
> Move change tracking

- guide-create-first-synchronization-data-management.rst
- guide-create-first-synchronization-data-synchronization.rst
- guide-create-first-synchronization.rst
- tutorial-getting-started-connect.rst
- tutorial-getting-started-enrich.rst
> Restructured getting started into synchronizaiton and management and fixed broken links for some tutorials

- index.rst
Dead link to design patterns page.
> Removed design patterns from Index

- features/durable-data.rst
> Moved important admonition

- index.rst
> Updated link to Operations

- documentation/data-synchronization/optimistic-locking-pattern.rst
- documentation/data-synchronization/share-patterns.rst
> added text for optimistic locking

- sesam-client.rst
- Re-write intro to attempt a more succinct explanation of the Sesam client
- Minor formatting adjustments
> Update Sesam client introduction

- features/change-tracking.rst
- features/integrated-search.rst
- features/property-lineage.rst
- management-studio.rst
- Expanded structure: subsections for each tab and panel
- Added sections for all left-menu items (Overview, Pipes, etc)
- Fleshed out and cleaned up explanations
- Fixed typos
- More consistent formatting
> IS-13488: Update Sesam Management Studio docs

- index.rst
> Added products section in index

- documentation/service-configuration/pipes/configuration-sinks.rst
- documentation/service-configuration/pipes/configuration-sources.rst
- documentation/service-configuration/pipes/configuration-transforms.rst
- documentation/service-configuration/systems/configuration-systems.rst
> added toc tree

- conf.py
> Add 5th nav level

- hub/documentation/data-synchronization/api-best-practices.rst
> making it easier to read

- talk/what-is-sesam-talk.rst
Test to see if this structure may work for the new model
> Testing new structure

- talk/what-is-sesam-talk.rst
As suggested by Inge here:
https://sesam.myjetbrains.com/youtrack/issue/IS-13964/Kan-vi-endre-litt-pa-https-docs.sesam.io-talk-what-is-sesam-talk.html https://sesam.zendesk.com/agent/tickets/7711
> Wording adjustment from Inge

- hub/documentation/service-configuration/systems/configuration-systems-rest.rst
Ref.:
- https://github.com/datanav/docs/pull/969/files#r1099824513
- https://sesam.slack.com/archives/C02F37XJ7T9/p1675846208560639
> IS-13742: Fixed typo in REST system, Jinja notation sesam:markjson

- index.rst
- talk/systems/index.rst
> Added sesam talk to index

- hub/dtl/dtl-functions-nulls.rst
Motivated by this Slack discussion: https://sesam.slack.com/archives/CPPGAVCEQ/p1681283861881299
> Rephrased the coalesce description to make it more explicit

- hub/features/data-management-features.rst
- hub/features/integrated-search.rst
- hub/features/property-lineage.rst
- talk/entity-types/index.rst
> Added note about payment method owner

- talk/index.rst
- talk/what-is-sesam-talk.rst
> Removed note about beta

- hub/data-transformation-language.rst
- hub/features/dependency-tracking.rst
> Added note and card for caveats page

- hub/documentation/service-configuration/systems/configuration-systems-microservice.rst
Add details on FQDN / default behavior of docker images
> Add details on FQDN / default behavior of docker images

- talk/selective-data-sync/index.rst
> Added example to selective data sync

- talk/systems/tripletex.rst
> Added info about employee token in TT

- hub/changelog.rst
So support have something to point at.
> Hibernation update

- talk/systems/hubspot.rst
> Added link to making hs talk

- .github/workflows/merge.yml
> Revert "IS-16251: Reverted azure/container-apps-deploy-action"

- talk/systems/wave.rst
> Moved FAQ for Wave

- talk/systems/hubspot.rst
- talk/systems/poweroffice.rst
> Add FAQ to HubSpot

- talk/concepts.rst
- talk/merging/index.rst
- talk/systems/index.rst
- talk/systems/tripletex.rst
> added merge FAQ

- talk/governance/index.rst
- talk/index.rst
> added gorvernance documentation

- talk/systems/hubspot.rst
> Added disable sync HS

- hub/documentation/service-configuration/pipes/configuration-transforms-template.rst
Also added missing default value for the ``operation_insert`` property.
> IS-16281: Documented the rewrite_update_payload_after_patch extension point

- hub/documentation/service-configuration/pipes/configuration-transforms-http.rst
- hub/documentation/service-configuration/pipes/configuration-transforms-rest.rst
Slack Thread:
https://sesam.slack.com/archives/C02F37XJ7T9/p1711094704010389
> Fix incorrect bool value for side_effects property

- talk/systems/businesscentral/faq/index.rst
- talk/systems/businesscentral/index.rst
Changes to Business Central intro and FAQ
> Schelvan patch 1

- hub/documentation/operations/security.rst
> Add docs permissions

- hub/features/compaction-feature.rst
> Re-write warning about compaction.keep_versions

- hub/features/integrated-search.rst
> Admonition Added for Read Permissions in Integrated Search

- hub/deprecations.rst
{
"type": "dtl",
"rules": {
"default": [
["merge",
["apply", "lower_keys", "_S."]
]
],
"lower_keys": [
["comment", "Lowercases all keys in a dictionary. Not recursive"],
["merge",
["apply", "lower_keys_iter",
["key-values", "_S."]
]
]
],
"lower_keys_iter": [
["add",
["lower", "_S.key"], "_S.value"]
]
}
}
> added non-recursive example

- hub/changelog.rst
- hub/documentation/service-configuration/pipes/configuration-transforms-http.rst
Ref [IS-17702](https://sesam.myjetbrains.com/youtrack/issue/IS-17702)
> IS-17702: Add trigger_on docs for http transform

- hub/documentation/connectors/patterns/handling-asymmetry.rst
> Is 17846 asymmetry

- hub/documentation/connectors/patterns/parameterized-datatypes.rst
> IS-17846: Added more information about share parameterized datatypes

- .gitignore
- hub/documentation/data-management/time-based-masterdata-management.rst
- hub/index-data-management.rst
> IS-17853: Added first draft on time-based masterdata management

- hub/documentation/data-synchronization/capture-response-with-transform-pattern.rst
- hub/documentation/service-configuration/pipes/configuration-transforms-rest.rst
> IS-17861: Added some text to capture-response-with-transform-pattern

- hub/documentation/data-synchronization/data-synchronization-patterns.rst
- hub/documentation/data-synchronization/namespace-split-pattern.rst
- hub/documentation/data-synchronization/transform-patterns.rst
> IS-17857: Added new transform patterns section and the namespace split pattern

- hub/bidirectional-synchronization.rst
- hub/documentation/data-synchronization/collect-patterns.rst
- hub/documentation/data-synchronization/data-synchronization-patterns.rst
- hub/documentation/data-synchronization/establish-origin-pattern.rst
- hub/index-synchronization.rst
> IS-17855: Added new version of bidirectional sync and fixed some other links

- hub/documentation/data-synchronization/update-pattern.rst
> added link and some extra text

- hub/documentation/service-configuration/pipes/configuration-sources-dataset.rst
Slack thread: https://sesam.slack.com/archives/CN58VU2UF/p1728375692832969
> Added note about subset lookup literals

- hub/index-developer.rst
- hub/index-synchronization.rst
> IS-17846-connectors-datasync: Merged connectors into data-synchronization and removed connector section in main documentation section

- hub/documentation/connectors/patterns/connector-patterns.rst
- hub/documentation/connectors/patterns/synthetic-properties.rst
> IS-17846-synthetic-properties: added synthetic properties

- hub/documentation/connectors/patterns/claims-pattern.rst
- hub/documentation/connectors/patterns/connector-patterns.rst
- hub/documentation/data-management/time-based-masterdata-management.rst
> claims-section: added a claims section and rewrote time-based masterdata management

- hub/deprecated-services.rst
- hub/index-developer.rst
- index.rst
> removed talk docs from index and added it too deprecated services

- hub/features/change-tracking.rst
> IS-17973: Added talk text to hub feature

- hub/enhanced-data-security.rst
- hub/index-developer.rst
> IS-17974: Moved data security to hub and alphabetically ordered documentation toctree

- community.rst
and practically dead travis-ci link.
> Remove abandoned firebase link
